### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by vitoramaral10** [MuntashirAkon/android-debloat-list#44]
I don't understand how to use this project? Do I put it inside a UAD folder or is it a UAD in itself?

please, help me.

**Comment by MuntashirAkon** [comment]
This project has no affiliations with UAD project in any way. You cannot use it in UAD since the format ADL uses is completely different from what UAD expects. While a JSON file might be created that would be compatible with UAD, this project is still a work in progress (WIP) and no release has been made yet.

**Comment by shuvashish76** [comment]
@Obegg

> As unfinished as it is - create a download/release for ADL so that users will have something that replaces UAD, that way they will see problems or have suggestions and report them back in order to improve the project.

Basically you're asking for supporting UAD compatible JSON releases. IMO this should be the lowest priority as supporting an _abandoned_ project makes no sense. It should be considered iff UAD becomes active again.
Since you asked in that issue I'm assuming you've gone through the whole discussion and you know that currently [AppManager](https://github.com/MuntashirAkon/AppManager) [[alpha](https://github.com/amcommunity/TipsAndTricks/issues/17)] is the only software that support ADL. Users are welcome to post their review if they find some descriptions are wrong or need improvements.

NOTE: Unlike UAD, AM is independent of this project which has it's own priorities hence nothing mentioned about it here officially. AM specific issues should be posted in that project only.

**Comment by vitoramaral10** [comment]
@shuvashish76  I understand, could you tell me which project I use this list with?

is it AppManager? do I import the json downloaded here into the app?

**Comment by shuvashish76** [comment]
AM User Manual is the official one, if it mentioned that way it must be true. If you've AM specific questions/issues you can ask in their issue tracker or in AM [Matrix](https://matrix.to/#/#appmanager:matrix.org) support room.

> Should be added to the README.md on the ADL GitHub page.

As mentioned ADL- work in progress, AM- alpha. ADL supported projects will be added with "how to use" when it's ready. Note that if you do use AM _Beta/Alpha/Debug_ versions you'll be considered as a tester.
