### ISSUE TITLE
Support for Android TV?

### ISSUE THREAD

**Issue by Obegg** [MuntashirAkon/android-debloat-list#45]
ADL requires an app to be installed on the device, and usually Android TVs don't play nicely with APKs which are not designed for it, 
I haven't tested ADL on Android TVs, though I can, but I guess I shouldn't waste my time unless the developer requests.

[Theoretically](https://github.com/0x192/universal-android-debloater/issues/910) it was possible to debloat Android TVs with UAD since everything was on the PC connected via USB, no need to install APK on the device itself.

**Comment by MuntashirAkon** [comment]
You can use App Manager (only the alpha version has ADL integrated) on Android TVs (App Manager supports all Android platforms since Lollipop). The UI is not currently optimised for Android TVs though and requires some time to adapt.

ADL is a platform independent data repository. It can't be used on its own. But my plan is to develop a static website (in a separate project) capable of debloating Android by utilising the USB permission, similar to what Graphene OS does to install their ROM. Other interested parties can create their own software, or even make it compatible with UAD (not that difficult, you'd only need to write a script that would generate a UAD compatible JSON out of the files in the repository).
